### ISSUE TITLE
Safari 12/OSX: Trackpad scrolling doesn't work or is jumpy over the iframe

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#174]
Constance and I noted that scrolling via our Mac laptop trackpads didn't work well when we were scrolling over the liveblog and big board iframes.

Behavior (when mouse is over the iframe):
- Page doesn't scroll at all
- Page scrolls if I try to scroll up and then down
- Page scrolls a little way and then stops

Also noticed this today in a few previous projects (including the 2016 election liveblog):
https://www.npr.org/2016/11/08/500427835/live-blog-election-night-2016
https://www.npr.org/2018/01/30/580378279/trumps-state-of-the-union-address-annotated
https://www.npr.org/sections/thetwo-way/2017/08/21/544239796/live-coverage-follow-the-solar-eclipse

But not in dailygraphics projects with tall graphics:
https://www.npr.org/sections/codeswitch/2017/11/04/560934698/indonesias-youth-share-thoughts-on-religion-identity-and-dreams
https://www.npr.org/2018/10/08/641625157/a-new-chinese-funded-railway-in-kenya-sparks-debt-trap-fears

**Comment by mileswwatkins** [comment]
Some research turns up:

- https://github.com/PierBover/ios-iframe-fix
- https://github.com/sachinchoolur/lightGallery/issues/672
- https://davidwalsh.name/scroll-iframes-ios

I'm playing around with these.

**Comment by mileswwatkins** [comment]
Huh, I cannot reproduce on Bailey's loaner iPad Mini, iOS 10 mobile Safari. I _can_ reproduce with the 2016 liveblog to a certain extent on macOS 10.13 Safari (scrolling up is always fine, but scrolling down is partially blocked), but not with the 2018 liveblog.

**Comment by mileswwatkins** [comment]
What if it's an issue with some component of the liveblog and fact-check, but _is not_ present for our other embeds?

**Comment by alykat** [comment]
To be clear: It's NOT a problem on iOS Safari. It's a problem with OSX/desktop Safari. (Yes, it's weird.)

And I was seeing it with the liveblog, factcheck AND elections graphics. (But not dailygraphics.)

**Comment by mileswwatkins** [comment]
Someone else found this, but said it was a yet-unfixed Safari bug: https://github.com/davidjbradshaw/iframe-resizer/issues/293#issuecomment-237300125

I've seen recommendations to set `onmousewheel` to null/empty, but a naive check on that didn't work. I've also seen comments that the issue is related to y-height manipulation, but we're not really doing that either.

Going to drop this and come back to it at a later date.

**Comment by shmcminn** [comment]
This does not seem to be a problem with users who have a scrollable mouse....

Watching at the timeline panel on Safari, it looks like the `scroll` event isn't being deployed on the downward trackpad scroll when user's mouse is inside an iframe. Also affecting the advertisement iFramed on the side.

**Comment by shmcminn** [comment]
After using web inspector to delete iframe within iframe on the live blog, scroll works for a few seconds and then stops again.

**Comment by shmcminn** [comment]
Final notes from looking at this today ... : 

- Problem does seem to only be on Safari desktop
- Problem exists using both "new" (live coverage) and "old" (big board) ways of embedding pyms 
- There are also cases where problem does NOT exist using both methods mentioned above (state pages and [Indonesia](https://www.npr.org/sections/codeswitch/2017/11/04/560934698/indonesias-youth-share-thoughts-on-religion-identity-and-dreams) story
- On scroll on the _working_ state pages, the following "scroll events" are dispatched (names shortended):
     - `pubads`
     - `pym v1`
     - `chartbeat`
     - `osd`
     - `0.9....chunk.js`
- On scroll on the _NOT_ working live blog page, the following "scroll events" are dispatched (names shortended):
     - `pubads`
     - `childtracker`
     - `chartbeat`
     - `osd`
     - `0.9....chunk.js`

Note that the `childtracker` event only fires on the non-working page, and the `pym v1` event only fires on the working page

**Comment by alykat** [comment]
In a branch, I tried updating the embed code to match dailygraphics (issue #60). Then, as test, I updated the code on the page for the House board and for the Alabama state page. Result: Still seeing the Safari scrolling bug, sadly. (But the updated embed code works.)

**Comment by alykat** [comment]
Another test: Commented out the overridecss for the liveblog and the Senate big board. Still no difference.

**Comment by mileswwatkins** [comment]
This is a captured event timeline from the only scenario in which you can scroll down on the liveblog in Safari with an Apple trackpad/MagicMouse: by scrolling up and _then_ immediately scrolling down. It looks like this triggers a single "Wheel" event (upwards) and _then_ a set of "Scroll" events downwards. Without the non-downwards "Wheel" event, the page does not recognize any downward "Scroll" events; confirmed that a rightwards "Wheel" or leftwards "Wheel" _also_ allow for downward "Scroll"s.

<img width="1218" alt="screen shot 2018-10-22 at 18 11 43" src="https://user-images.githubusercontent.com/4959135/47322454-fc4f7580-d625-11e8-9e6a-e4a8f8c0304b.png">

**Comment by mileswwatkins** [comment]
With a "normal" mouse (eg, our USB Dell mice with a physical scroll wheel), scrolling produces a series of individual "Wheel"s followed by individual "Scroll"s. Furthermore, a downward "Scroll" event _is_ allowed!

<img width="1382" alt="screen shot 2018-10-22 at 18 18 06" src="https://user-images.githubusercontent.com/4959135/47322710-fb6b1380-d626-11e8-962c-b64bb5659c4c.png">

**Comment by mileswwatkins** [comment]
Unlikely, but any chance this error is related to the Analytics module, sorta analogous to https://github.com/nprapps/elections18-graphics/issues/184#issuecomment-432033517?

**Comment by mileswwatkins** [comment]
More resources:

- https://github.com/promo/wheel-indicator#api
- https://github.com/jquery/jquery-mousewheel/issues/36
- https://stackoverflow.com/questions/12727219/how-to-check-each-new-scroll-and-avoid-apple-mouses-issue-multiple-scroll-effec

**Comment by mileswwatkins** [comment]
It seems that if you delete this stylesheet from the `<head>` of the liveblog embed within the Seamus page, then scrolling down works! Time for me to investigate :)

<img width="669" alt="screen shot 2018-11-01 at 10 53 15" src="https://user-images.githubusercontent.com/4959135/47859331-79b47c00-ddc4-11e8-9dd8-75d586091362.png">

**Comment by mileswwatkins** [comment]
Ugh, so I still think the issue is related to that CSS file, but going into that file and deleting specific elements gets a different result each time; I'm not convince that a single specific line in there can be blamed! For example, in two different cases I deleted specific lines in order to get the liveblog scroll-down working:

```
p.header-info {
    font-family: 'Gotham SSm', Helvetica, Arial, sans-serif;
    font-weight: normal;
    font-weight: 400;
    -webkit-font-smoothing: antialiased;
    color: #767676;
    font-size: 12px;
    -webkit-font-smoothing: auto;
    margin-bottom: 1.5125rem        <- this
}
```

and

```
html {
    font-size: 14px;
    line-height: 1        <- this
}
```

But on subsequent refreshes, removing those lines didn't have the desired effect.

Maybe Safari `iframe`s have a _maximum amount_ of CSS computation allowed? Ugh.

**Comment by mileswwatkins** [comment]
Okay, effectively solved, wow.

It looks like this was caused by a _combination_ of the `what-input` library ([GH repo](https://github.com/ten1seven/what-input)) loaded in Seamus by DM, and a few select lines in the `app.less` file (, plus macOS Safari's special handling of Apple-brand trackpad/mouse scroll events, and scrolling over `iframe`s).

To test, I injected `what-input` into the `localhost` testing page for the liveblog. Basically, this just entails copying the JS from [here](https://github.com/ten1seven/what-input/blob/master/dist/what-input.js) and pasting it inside a `script` tag in the `<head>` of `templates/_base.html`; this, for our debugging purposes, "emulates" the embed being on Seamus.

I've commented out these three problematic lines of Less. @alykat, I'm passing this task off to you, to identify functioning replacements for these lines. I'm also going to do the same for the `board-ballot` embed, which seems to be the only other one that suffers this issue.

**Comment by mileswwatkins** [comment]
@alykat, my commenting-out of these three lines from the liveblog Less (https://github.com/nprapps/liveblog/commit/e748a64f3233d0aea0b8687e10249f64a5628574), and one tag from the NPR footer Less (https://github.com/nprapps/elections18-graphics/commit/933d6f469848d32b09f1f156f130547ad3d93ed1) seem to have fixed the Safari scroll-down problem. Once you find functioning replacements for those four style lines (by far the most important is the `position: absolute` for the Liveblog tooltips), then this ticket can finally be closed out!
