### ISSUE TITLE
Double-check anything related to time after the DST change

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#183]
We fall back the weekend before the election. Look at poll closing times, last updated timestamps, etc.

This usually isn't a problem, but it's good to check anyway.

**Comment by mileswwatkins** [comment]
I believe that all timestamps say "ET" rather than something else, presumably because we'd been burned in the past.

- AP serves as a UTC timestamp: `"lastUpdated": "2018-10-17T13:45:06.36Z"`
- Elex doesn't alter this field
- Postgres stores it as a `DateTimeField`, still with no timezone localization
- There's a back-end function in `fabfile/utils.py` named `_set_timezone()` that localizes all dates, times, and datetimes in the rendered JSON to Eastern Time (agnostic of daylight saving):

```
def _set_timezone(value):
    datetime_obj_utc = value.replace(tzinfo=timezone('GMT'))
    datetime_obj_est = datetime_obj_utc.astimezone(timezone('US/Eastern'))
    return datetime_obj_est
```
