### ISSUE TITLE
Cross-origin error when scrolling down the page

### ISSUE THREAD

**Issue by alykat** [nprapps/elections18-graphics#184]
When I look at the graphics w/in the context of Seamus pages, I get a cross-origin error. For example, a state page:

![image](https://user-images.githubusercontent.com/491318/47166776-f0cd1900-d2ca-11e8-9d57-88aaf8647add.png)

This seems to be the related code:

![image](https://user-images.githubusercontent.com/491318/47166961-5caf8180-d2cb-11e8-9d9f-00e9eea0caa7.png)

This is not present w/ the 2016 boards -- see https://www.npr.org/2016/11/08/499287941/2016-senate-race-election-results -- so this must be something new from this year?

**Comment by mileswwatkins** [comment]
Currently _not_ happening on the House board, but happening on the other three. Hmm!

**Comment by mileswwatkins** [comment]
Ohhh, I think this is due to a Google Analytics on-scroll page-completion-event failure. Because the `iframe`s for certain states or board types are so (vertically) short, scrolling tries to trigger a completion-percentage event, but the bottom of the browser viewport is _already below_ the bottom of the `iframe`, thus breaking the scroll-tracking function and throwing an error.

**Comment by alykat** [comment]
Also worth noting that I used updated emped code for the House board, to test a theory for the Safari bug. https://github.com/nprapps/elections18-graphics/issues/174#issuecomment-431682945 I need to change it back (or change all the others).
