### ISSUE TITLE
If independent wins a House race, the BoP bar-chart label won't work

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#197]
<img width="527" alt="screen shot 2018-10-22 at 13 17 57" src="https://user-images.githubusercontent.com/4959135/47307425-fa24f100-d5fc-11e8-98c8-9bcf84b0b4b3.png">

Essentially unlikely to happen though

**Comment by alykat** [comment]
Bringing this back b/c of AK-House

**Comment by mileswwatkins** [comment]
It looks like the Alaska House race is still a two-person, major-party-only contest, right? ([FTE](https://projects.fivethirtyeight.com/2018-midterm-election-forecast/house/alaska/1/), [RCP](https://www.realclearpolitics.com/epolls/2018/house/ak/alaska_atlarge_district_young_vs_galvin-6699.html))

**Comment by alykat** [comment]
Updated the code so that independent winners in the House go to the D side of the bar, which should cover us for the AK case if that goes that way. Will need to verify footnote language (and when it should be deployed) w/ Arnie.

![image](https://user-images.githubusercontent.com/491318/47959583-84d2fc00-dfbe-11e8-9735-3696a9267985.png)

Doesn't solve the problem entirely (what if there's a major third-party GOP-friendly candidate next time around?), but maybe addresses it for now.

**Comment by mileswwatkins** [comment]
Very good catch. The AP API lists her party as `Udl`, even though she won the Democratic nomination later on.

Another option would be to override her party value to `Dem`; maybe that would be editorially clearer?

**Comment by mileswwatkins** [comment]
I'll also need to update the BoP/chamber-calling logic to handle this individual, if we don't hard-code her to `Dem`.

**Comment by mileswwatkins** [comment]
It looks like we could insert a party override via Peewee/SQL, right before finishing results-load:

https://github.com/nprapps/elections18-general/blob/master/fabfile/data.py#L153-L156

**Comment by mileswwatkins** [comment]
<img width="710" alt="screen shot 2018-11-05 at 13 32 16" src="https://user-images.githubusercontent.com/4959135/48018600-43963580-e0ff-11e8-9970-196f514853d0.png">
