### ISSUE TITLE
Board header spacing incorrect on iOS

### ISSUE THREAD

**Issue by mileswwatkins** [nprapps/elections18-graphics#213]
Cannot reproduce outside of iOS; this bug is not present on Android, and not reproducible using browser emulation tools on desktop. But it is present across iOS Safari, Chrome, and Firefox, on multiple devices. Present in both single- and two-column view.

<img width="638" alt="screen shot 2018-10-30 at 10 24 18" src="https://user-images.githubusercontent.com/4959135/47725033-2e686500-dc2e-11e8-8c37-7fd0425f2bd4.png">

**Comment by alykat** [comment]
Mostly fixed, or at least hopefully not terribly noticeable anymore. Was caused by the table row I inserted to use `table-layout: fixed` to help address problems with errant table column widths and super-long names.

![image](https://user-images.githubusercontent.com/491318/47754173-6395a700-dc70-11e8-92c3-060da03f3995.png)
